project:
  type: default
  output-dir: ../reports

lang: es

resources:
  - .quartoAssets/paged.polyfill.js
  - .quartoAssets/preview.css
  - .quartoAssets/print.css
  - .quartoAssets/styles.css
  - .quartoAssets/counter-off.css

format:
  html:
    include-in-header:
      - text: |
          <!-- PagedJS for live preview -->
          <script src=".quartoAssets/paged.polyfill.js"></script>
          <link rel="stylesheet" href=".quartoAssets/preview.css" media="screen">
    css:
      - .quartoAssets/styles.css
      - .quartoAssets/table-styles.css
    fig-format: png
    fig-dpi: 300

  pdf-paged:
    pagedjs: true
    number-sections: true
    css:
      - .quartoAssets/styles.css
      - .quartoAssets/table-styles.css
    margin-left: 1in
    margin-right: 1in
    margin-top: 1in
    margin-bottom: 1in
    documentclass: scrartcl
    papersize: A4
    classoption: [a4paper]
    fig-format: png
    fig-dpi: 300

  pdf:                
    pdf-engine: lualatex
    number-sections: true
    toc: true
    toc-depth: 2
    papersize: a4
    margin-left: 2cm
    margin-right: 2cm
    margin-top: 2cm
    margin-bottom: 2cm
    colorlinks: true
    fig-format: png
    fig-dpi: 300
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{geometry}
          \usepackage{fancyhdr}
          \usepackage{fontspec}
          \usepackage{setspace}
          \usepackage{tocloft}
          \usepackage{hyperref}
          \usepackage{tabularx}
          \usepackage{booktabs}
          \usepackage{array}
          \usepackage{ragged2e}
          \usepackage{graphicx}
          \usepackage{url}
          \setmainfont{Times New Roman}
          \fontsize{12}{12}\selectfont
          \setcounter{tocdepth}{2}
          % Columna que hace wrap automático
          \newcolumntype{L}{>{\raggedright\arraybackslash}X}
          \pagestyle{fancy}
          \fancyhf{}
          \rfoot{\thepage}
          \renewcommand{\headrulewidth}{0pt}
          \linespread{1.0}
          \setlength{\baselineskip}{12pt}
          \setlength{\parskip}{0pt}
          \setlength{\parsep}{0pt}
          \setlength{\headsep}{0pt}
          \setlength{\footskip}{0pt}
          \setlength{\textheight}{24cm}
