project:
  type: default
  output-dir: ../reports

lang: es

# Solo LuaLaTeX - sin recursos HTML

format:
  pdf:                
    pdf-engine: lualatex
    number-sections: true
    toc: true
    toc-depth: 2
    papersize: a4
    margin-left: 2cm
    margin-right: 2cm
    margin-top: 2cm
    margin-bottom: 2cm
    colorlinks: true
    fig-format: png
    fig-dpi: 300
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{geometry}
          \usepackage{fancyhdr}
          \usepackage{fontspec}
          \usepackage{setspace}
          \usepackage{tocloft}
          \usepackage{hyperref}
          \usepackage{tabularx}
          \usepackage{booktabs}
          \usepackage{array}
          \usepackage{ragged2e}
          \usepackage{graphicx}
          \usepackage{url}
          \setmainfont{Times New Roman}
          \fontsize{12}{12}\selectfont
          \setcounter{tocdepth}{2}
          % Columna que hace wrap automático
          \newcolumntype{L}{>{\raggedright\arraybackslash}X}
          % Configuración para carátula centrada
          \usepackage{titling}
          \setlength{\droptitle}{-2cm}
          \pretitle{\begin{center}\LARGE}
          \posttitle{\end{center}}
          \preauthor{\begin{center}\large}
          \postauthor{\end{center}}
          \predate{\begin{center}\large}
          \postdate{\end{center}}
          % Configuración para TOC en página separada
          \usepackage{tocloft}
          \renewcommand{\cfttoctitlefont}{\hfill\Large\bfseries}
          \renewcommand{\cftaftertoctitle}{\hfill}
          % Forzar TOC en página separada
          \usepackage{etoolbox}
          \pretocmd{\tableofcontents}{\clearpage}{}{}
          \pagestyle{fancy}
          \fancyhf{}
          \rfoot{\thepage}
          \renewcommand{\headrulewidth}{0pt}
          \linespread{1.0}
          \setlength{\baselineskip}{12pt}
          \setlength{\parskip}{0pt}
          \setlength{\parsep}{0pt}
          \setlength{\headsep}{0pt}
          \setlength{\footskip}{0pt}
          \setlength{\textheight}{24cm}
